### ISSUE TITLE
Don't persist peer IP addresses permanently

### ISSUE THREAD

**Issue by enc0urage** [ddosecrets/torrent-health-monitor#1]
Hi,

Reading the source code of this repository, it seems that in the current implementation it persists the IP address of everybody who downloaded a torrent in a postgres database, permanently. I don't think keeping this data is necessary to provide the intended functionality to monitor the current health of a torrent and it creates a possible privacy issue.

I also don't think hashing the IP addresses would be a feasible solution as the IPv4 address space is quite small, so whatever hashing algorithm would be too easy to bruteforce.

As a middle of the ground solution, I'd suggest keeping the IP addresses in an in-memory sqlite database (in a file, on tmpfs, so the database can still be shared between the python and ruby codebase) that doesn't persist across reboots or unexpected shutdowns. Additionally, this sqlite file could be recreated every time the trackers and the DHT are scraped, as I don't see any reason to keep data about stale peers.

**Comment by milo-trujillo** [comment]
Hi, thanks for the feedback!

There was a cronjob and script I neglected to add to this repo that prunes old records from the database. I'll add that momentarily. You're absolutely right, the intent was not to create a permanent log, I just missed a (critical) script in the push. Since the UI doesn't include any information more than one month old, there's no need to maintain records for more than 30 days.

I also agree on the limitations of hashing here - at best, hashing IPv4 addresses could be considered akin to ROT13 in that it protects against a casual observer unintentionally reading an address, but offers no meaningful security.

I'm apprehensive about the SQLite solution, because we could have concurrent database writes from both the Ruby code (reading trackers) and the Python code (reading the DHT), as well as (theoretically) from a script adding new torrents to be tracked. There are no difficulties sharing data with the read-only UI this way, but I chose Postgres over SQLite so I wouldn't have to build some kind of locking mechanism to maintain database integrity.

**Comment by milo-trujillo** [comment]
Data pruning script pushed to the repository and included in documentation

**Comment by milo-trujillo** [comment]
Happy to continue this conversation, but I'll mark this issue as closed since peer IP addresses are no longer logged indefinitely in the current main branch

**Comment by milo-trujillo** [comment]
Hmm, is it necessary to trigger a vacuum manually here? My understanding was auto-vacuum would regularly reclaim deleted rows - granted, not at the exact time the "prune month-old data" script runs, but whenever automatic cleanup next occurs. Since a manual vacuum locks the entire table, copies all data, and deletes the original, it'd be preferable not to trigger that much more than we need to. For example, while marking old data for deletion every minute and functionally removing it from the peers table is fine, locking and replacing the entire peer table every minute would be overkill.

The default postgres behavior appears to be "check whether auto-vacuum is necessary once per minute, but only trigger a vacuum if at least 20% of table size + 50 tuples have been deleted." Based on some back-of-napkin math and the peer data for the torrents we're monitoring, this'll occur roughly every five days or sooner in our environment. Of course, if you're monitoring very few torrents with few peers, the auto-vacuum might not trigger for longer - but then again, even a manual vacuum doesn't guarantee that the data is overwritten on the disk, only that postgres releases the blocks. This is garbage collection, not forensic-grade data wiping.
